filebeat.prospectors:
- paths:
    - /data/*.log
  input_type: log
  json.keys_under_root: true

output.elasticsearch:
  hosts: ["10.0.0.10:9200"]
  index: "boc-%{+yyyy.MM.dd}"
  template.name: "boc"
  template.path: "filebeat.template.json"
  template.overwrite: true
