filebeat.prospectors:
- input_type: log
  paths:
    - /data/*.log

output.elasticsearch:
  hosts: ["10.0.0.10:9200"]
#  template.name: "filebeat"
#  template.path: "filebeat.template.json"
#  template.overwrite: false
